export const matches = [
    {
        id: 1,
        status: "LIVE",
        tournament: "T20 World Cup",
        venue: "Dubai International Stadium",
        team1: "India",
        score1: "184/4",
        overs1: "20.0",
        team2: "Australia",
        score2: "142/6",
        overs2: "16.2",
        summary: "Australia needs 43 runs in 22 balls",
        team2Winner: false,
    },
    {
        id: 2,
        status: "FINISHED",
        tournament: "ODI Series",
        venue: "Lord's, London",
        team1: "England",
        score1: "284/10",
        overs1: "48.2",
        team2: "New Zealand",
        score2: "285/4",
        overs2: "46.5",
        summary: "New Zealand won by 6 wickets",
        team2Winner: true,
    },
    {
        id: 3,
        status: "LIVE",
        tournament: "Test Series",
        venue: "MCG, Melbourne",
        team1: "South Africa",
        score1: "312 & 142/3",
        overs1: "45.0",
        team2: "Pakistan",
        score2: "280",
        overs2: "89.4",
        summary: "South Africa lead by 174 runs",
        team2Winner: false,
    },
    {
        id: 4,
        status: "UPCOMING",
        tournament: "T20 Series",
        venue: "Eden Gardens, Kolkata",
        team1: "India",
        score1: "Yet to bat",
        overs1: "0.0",
        team2: "Sri Lanka",
        score2: "Yet to bat",
        overs2: "0.0",
        summary: "Match starts at 19:00 IST",
        team2Winner: false,
    }
];
